name: "Benchmarks"

on:
  pull_request:
  push:

jobs:
  benchmarks:
    name: "Run benchmarks"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.2"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4.2.2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.31.1"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "PhpBench"
        run: "make phpbench"
